#   This file is part of DigiLog-API.
#
#   DigiLog-API is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   DigiLog-API is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with DigiLog-API.  If not, see <http://www.gnu.org/licenses/>.

package DigiLog::Config;
use strict;
use warnings;

=head1 NAME

DigiLog::Retrieve - Retrieve log data from a DigiLog setup

=head1 DESCRIPTION

Module used, along with other classes in DigiLog-API, to provide access to the
log files generated by DigiLog (available from L<http://www.broadcastsoftware.org>)

=head1 CONSTRUCTOR

=over 4

=item new ( $location, $length )

Creates a DigiLog::Config with the appropriate parameters. There are two
mandatory arguments.

=over 4

=item $location

The path to the directory containing the logs

=item $length

The length (in seconds) of a the individual log files

=back

=cut

sub new {
    my ($class, $location, $length) = @_;
    if ((!$location) and (!$length)) {
        $@ = "Insufficient parameters passed. Both \$location and \$length are required.";
        return undef;
    }
    my $self = bless {}, $class;
    $self->{location} = $location;
    $self->{length} = $length;
    return $self;
}

=back

=head1 METHODS

=over 4

=back

=head1 COPYRIGHT

Copyright (c) 2010 Chris Hawley E<lt>F<chris@phenorbital.co.uk>E<gt>
All rights reserved.
This program is free software; you can redistribute itand/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
at your option) any later version.
=cut

1;
