#   This file is part of DigiLog-API.
#
#   DigiLog-API is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   DigiLog-API is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with DigiLog-API.  If not, see <http://www.gnu.org/licenses/>.

package DigiLog::Retrieve;

use strict;
use IO::Dir;

use DigiLog::Config;

=head1 NAME

DigiLog::Retrieve - Retrieve log data from a DigiLog setup

=head1 DESCRIPTION

Module used, along with other classes in DigiLog-API, to provide access to the
log files generated by DigiLog (available from L<http://www.broadcastsoftware.org>)

=head1 METHODS

=over 4

=cut

=item available_times

Returns a list containing two items, the first and last available times within
the log location specified in the configuration object. No checks are performed
to ensure that all times within this range are available.

=cut
sub available_times {
    my $dir = new IO::Dir($main::config->{location})
        or die("Couldn't open directory $main::config->{location}");
    
    my @files;
    
    FILE:
    for my $file($dir->read()) {
        if ($file =~ /^[0-9]+\.0$/) {
            push (@files, $file);
        }
    }
    
    if (!@files) {
        die("No files found in $main::config->{location}");
    }
    
    my @sorted_files = sort(@files);
    my ($first, undef) = split(/\./, $sorted_files[0]);
    my ($last, undef) = split(/\./, $sorted_files[$#sorted_files]);
    
    return($first, $last-1);
}

=back

=head1 COPYRIGHT

Copyright (c) 2010 Chris Hawley E<lt>F<chris@phenorbital.co.uk>E<gt>
All rights reserved.
This program is free software; you can redistribute itand/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
at your option) any later version.
=cut

1;
